/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lyp_com_ndkmodeo_NDKUtil */

#ifndef _Included_lyp_com_ndkmodeo_NDKUtil
#define _Included_lyp_com_ndkmodeo_NDKUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lyp_com_ndkmodeo_NDKUtil
 * Method:    SaySometing
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lyp_com_ndkmodeo_NDKUtil_SaySometing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
